# Dictionary of maps with dimensions and base colors for procedural terrain generation.
# UNIT_CLASSES defines stats for all unit and building types: cost, health, speed, weapons, etc.


MAPS = {
    "Desert": {"width": 2560, "height": 2560, "color": (139, 120, 80)},
    "Forest": {"width": 3200, "height": 3200, "color": (34, 100, 34)},
    "Ice": {"width": 2560, "height": 2560, "color": (180, 200, 220)},
    "Urban": {"width": 5000, "height": 5000, "color": (100, 100, 100)},
}

UNIT_CLASSES = {
    "Infantry": {
        "cost": 100,
        "hp": 45,
        "speed": 0.7,
        "attack_range": 140,
        "sight_range": 120,
        "weapons": [
            {
                "name": "Rifle",
                "damage": 10,
                "fire_rate": 0.5,
                "projectile_speed": 25,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 25,
            }
        ],
        "size": (16, 16),
        "air": False,
        "is_building": False,
        "height": 8,
        "rifle_length": 2.0,
        "rifle_thickness": 0.4,
    },
    "Marksman": {
        "cost": 150,
        "hp": 45,
        "speed": 0.6,
        "attack_range": 150,
        "sight_range": 150,
        "weapons": [
            {
                "name": "Sniper",
                "damage": 25,
                "fire_rate": 0.3,
                "projectile_speed": 30,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 60,
            }
        ],
        "size": (16, 16),
        "air": False,
        "is_building": False,
        "height": 6,
        "rifle_length": 2.5,
        "rifle_thickness": 0.3,
    },
    "Tank": {
        "cost": 700,
        "hp": 300,
        "speed": 0.8,
        "attack_range": 80,
        "sight_range": 200,
        "weapons": [
            {
                "name": "Cannon",
                "damage": 80,
                "fire_rate": 0.6,
                "projectile_speed": 30,
                "projectile_length": 1,
                "projectile_width": 2,
                "cooldown": 50,
            }
        ],
        "size": (30, 20),
        "air": False,
        "is_building": False,
        "height": 5,
        "turret_width": 12,
        "turret_depth": 8,
        "turret_height": 3,
        "barrel_length": 20,
        "barrel_width": 3,
        "barrel_height": 4,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.05,
        "turret_rotation_speed": 0.15,
    },
    "HeavyTank": {
        "cost": 1200,
        "hp": 500,
        "speed": 0.6,
        "attack_range": 90,
        "sight_range": 220,
        "weapons": [
            {
                "name": "Heavy Cannon",
                "damage": 120,
                "fire_rate": 0.4,
                "projectile_speed": 25,
                "projectile_length": 2,
                "projectile_width": 3,
                "cooldown": 70,
            }
        ],
        "size": (40, 25),
        "air": False,
        "is_building": False,
        "height": 6,
        "turret_width": 16,
        "turret_depth": 10,
        "turret_height": 4,
        "barrel_length": 25,
        "barrel_width": 4,
        "barrel_height": 5,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.05,
        "turret_rotation_speed": 0.15,
    },
    "TankDestroyer": {
        "cost": 900,
        "hp": 250,
        "speed": 0.7,
        "attack_range": 150,
        "sight_range": 250,
        "weapons": [
            {
                "name": "Destroyer Gun",
                "damage": 150,
                "fire_rate": 0.3,
                "projectile_speed": 35,
                "projectile_length": 1,
                "projectile_width": 2,
                "cooldown": 90,
            }
        ],
        "size": (35, 22),
        "air": False,
        "is_building": False,
        "height": 5,
        "turret_width": 14,
        "turret_depth": 9,
        "turret_height": 3,
        "barrel_length": 30,
        "barrel_width": 3,
        "barrel_height": 4,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.05,
        "turret_rotation_speed": 0.15,
    },
    "Grenadier": {
        "cost": 300,
        "hp": 45,
        "speed": 0.7,
        "attack_range": 100,
        "sight_range": 120,
        "weapons": [
            {
                "name": "Grenade",
                "damage": 20,
                "fire_rate": 0.5,
                "projectile_speed": 15,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 20,
            }
        ],
        "size": (16, 16),
        "air": False,
        "is_building": False,
        "height": 8,
        "rifle_length": 1.8,
        "rifle_thickness": 0.3,
    },
    "RocketSoldier": {
        "cost": 200,
        "hp": 45,
        "speed": 0.7,
        "attack_range": 140,
        "sight_range": 130,
        "weapons": [
            {
                "name": "Rocket",
                "damage": 120,
                "fire_rate": 0.3,
                "projectile_speed": 8,
                "projectile_length": 2,
                "projectile_width": 2,
                "cooldown": 80,
            }
        ],
        "size": (16, 16),
        "air": False,
        "is_building": False,
        "height": 8,
        "rocket_length": 1.8,
        "rocket_thickness": 0.3,
    },
    "MachineGunVehicle": {
        "cost": 500,
        "hp": 200,
        "speed": 0.9,
        "attack_range": 120,
        "sight_range": 200,
        "weapons": [
            {
                "name": "MG",
                "damage": 25,
                "fire_rate": 0.5,
                "projectile_speed": 10,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 50,
            }
        ],
        "size": (35, 25),
        "air": False,
        "is_building": False,
        "height": 6,
        "turret_width": 9,
        "turret_depth": 6,
        "turret_height": 2,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.05,
        "turret_rotation_speed": 0.15,
    },
    "RocketArtillery": {
        "cost": 800,
        "hp": 150,
        "speed": 0.7,
        "attack_range": 150,
        "sight_range": 175,
        "weapons": [
            {
                "name": "Rockets",
                "damage": 200,
                "fire_rate": 0.1,
                "projectile_speed": 10,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 150,
            }
        ],
        "size": (40, 25),
        "air": False,
        "is_building": False,
        "height": 8,
        "turret_width": 20,
        "turret_depth": 8,
        "turret_height": 6,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.05,
        "turret_rotation_speed": 0.15,
    },
    "AttackHelicopter": {
        "cost": 1000,
        "hp": 200,
        "speed": 0.9,
        "attack_range": 100,
        "sight_range": 175,
        "weapons": [
            {
                "name": "Missiles",
                "damage": 30,
                "fire_rate": 0.5,
                "projectile_speed": 10,
                "projectile_length": 1,
                "projectile_width": 1,
                "cooldown": 40,
            }
        ],
        "size": (25, 15),
        "air": True,
        "fly_height": 10,
        "is_building": False,
        "height": 4,
        "turret_width": 5,
        "turret_depth": 3,
        "turret_height": 1,
        "turret_offset_x": 0,
        "turret_offset_y": 0,
        "hull_rotation_speed": 0.08,
        "turret_rotation_speed": 0.2,
    },
    "Headquarters": {
        "cost": 1000,
        "starting_credits": 7500,
        "hp": 500,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "size": (40, 40),
        "air": False,
        "is_building": True,
        "height": 35,
    },
    "Barracks": {
        "cost": 300,
        "hp": 200,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "producible": ["Infantry", "Grenadier", "RocketSoldier", "Marksman"],
        "production_time": 60,
        "size": (32, 32),
        "air": False,
        "is_building": True,
        "height": 25,
    },
    "WarFactory": {
        "cost": 500,
        "hp": 200,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "producible": [
            "Tank",
            "HeavyTank",
            "TankDestroyer",
            "MachineGunVehicle",
            "RocketArtillery",
        ],
        "production_time": 60,
        "size": (40, 32),
        "air": False,
        "is_building": True,
        "height": 30,
    },
    "Hangar": {
        "cost": 600,
        "hp": 200,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "producible": ["AttackHelicopter"],
        "production_time": 90,
        "size": (36, 28),
        "air": False,
        "is_building": True,
        "height": 20,
    },
    "PowerPlant": {
        "cost": 300,
        "hp": 200,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "size": (32, 32),
        "air": False,
        "is_building": True,
        "height": 15,
    },
    "Refinery": {
        "cost": 2000,
        "hp": 200,
        "speed": 0,
        "attack_range": 0,
        "sight_range": 200,
        "weapons": [],
        "income": 150,
        "income_interval": 300,
        "size": (48, 32),
        "air": False,
        "is_building": True,
        "height": 25,
    },
    "Turret": {
        "cost": 400,
        "hp": 200,
        "speed": 0,
        "attack_range": 300,
        "sight_range": 200,
        "weapons": [
            {
                "name": "TurretGun",
                "damage": 20,
                "fire_rate": 0.67,
                "projectile_speed": 5,
                "projectile_length": 10,
                "projectile_width": 4,
                "cooldown": 30,
            }
        ],
        "size": (24, 24),
        "air": False,
        "is_building": True,
        "height": 25,
        "hull_rotation_speed": 0.0,
        "turret_rotation_speed": 0.1,
    },
}
